remote_theme: pages-themes/midnight
plugins: 
 - jekyll-remote-theme
include: /assets/css/style.scss
title: "<a href='/public-memos/'>public memos</a>"
description: "A public note, written casually."
show_downloads: false
